name: 'finance_dwh_solutions'
version: '1.0'
config-version: 2

profile: 'finance_dwh_solutions'

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

